### ISSUE TITLE
CI workflow fails on Node.js 18 for CentOS Stream/RHEL 9

### ISSUE THREAD

**Issue by richardlau** [RedHatInsights/insights-js-client#16]
The last two daily workflows have failed to build Node.js 18 on CentOS Stream 9 due to running out of disk space.

e.g. https://github.com/RedHatInsights/insights-js-client/actions/runs/7770196981
![image](https://github.com/RedHatInsights/insights-js-client/assets/5445507/83a1ee4f-d68e-4663-bba9-135ae7884763)

This happens to be the combination where the ccache is much larger (2 GB vs 160-180MB).

**Comment by richardlau** [comment]
There was a bunch of stuff updated in the new runner image which could all be contributing to a reduced amount of available disk space: https://github.com/actions/runner-images/pull/9275

**Comment by richardlau** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories the ubuntu runners should have 150GB storage so it's surprising to run out of space.

I did a quick run on a local server and for CentOS Stream 9 the `~/rpmbuild` dir grows to 19GB during the rebuild. With the ccache that would take us to around 23GB.

**Comment by richardlau** [comment]
Running some debug on the runners -- prior to us building anything, the available space on the runner is:
```console
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   55G   19G  75% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
```

which doesn't seem to tally with https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories.

There may be some things we can delete from the runner as a workaround: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

**Comment by richardlau** [comment]
> According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories the ubuntu runners should have 150GB storage so it's surprising to run out of space.

Supposedly 150GB was a [documentation error](https://github.com/actions/runner-images/issues/9344#issuecomment-1942811369).

**Comment by rdruss** [comment]
Seems like an order of magnitude documentation error 😮
